Swupdate bugs
seapath/meta-seapath pull request #58
Opened 2022-01-20 17:24 UTC by insatomcat

fixes 2 bugs with swupdate:

    switch_bootloader.sh: fix for some UEFI behavior
    Some UEFI firmware tend to remove from the boot order all slots that are
    explicitely disabled (if they are disabled, they have nothing to do in
    the boot order).
    switch_bootloader.sh assume both Seapath slots are present in the boot
    order, but since the UEFI may have removed the disabled slot, this may
    not be the case.
    This fix makes switch_bootloader.sh working even if both slots are not
    in the boot order

    system-config: fix typo in swupdate_hawkbit.sh
    Fix typo in check_health.

2022-01-21 08:42 UTC, ebail requested changes
Hi Thanks for your work.

I would rework the commit message. It might sound picky but I believe it is important for the history of the project.

As described in https://github.com/seapath/.github/blob/main/CONTRIBUTING.md#styleguides,
please "Use the imperative mood in the subject line". 

I would commit:

system-config: fix typo in swupdate_hawkbit.sh

Fix typo in check_health.

2022-01-21 08:42 UTC, ebail requested changes
Hi Thanks for your work.

I would rework the commit message. It might sound picky but I believe it is important for the history of the project.

As described in https://github.com/seapath/.github/blob/main/CONTRIBUTING.md#styleguides,
please "Use the imperative mood in the subject line". Please explain what your are doing,

2022-01-24 08:52 UTC, dupremathieu approved these changes

2022-01-31 10:35 UTC, ebail approved these changes
LGTM, Thanks

2022-01-31 11:55 UTC, merged