kernel parameters: disable IPv6
seapath/meta-seapath pull request #60
Opened 2022-01-20 17:31 UTC by insatomcat

IPv6 in SEAPATH has not been taken into account and tested. For security
reasons it is better to disable it.
The IPv6 disabling is done in kernel parameters to avoid givin the
possibility de re-enabled at runtime.
The IPv6 can easily be restored if necessary by deleting the kernel
parameter.

Signed-off-by: insatomcat <florent.carli@rte-france.com>

2022-01-21 08:31 UTC, ebail requested changes
Hi Thanks for your work.

I would rework the commit message. It might sound picky but I believe it is important for the history of the project.

As described in https://github.com/seapath/.github/blob/main/CONTRIBUTING.md#styleguides,
please "Use the imperative mood in the subject line". Please explain what your are doing, it looks like you are taking libvirt from somewhere else, right ? Is it from meta-virtulization. Please explain it.

I would commit:

grub-efi: disable ipv6

Disable ipv6 because X, Y and Z.

Thanks

2022-01-21 09:06 UTC, dupremathieu commented
> I know it would be better to do it directly in the kernel config, but in the meantime this is quick and easy

It's seemed ok to deactivate IPv6 using kernel parameters. It is a good compromise, with this we can be sure that it can't be reactivated later in runtime and it's easy to re-enabled it, during the generation for those who need it.

I think we could go even further by making this deactivation configurable. I am adding in the *external_parameters* branch the possibility to configure some aspects of SEAPATH like the keymap and the configuration of some kernel parameters like CPU isolation. It could be done in another PR.

2022-01-21 09:24 UTC, dupremathieu requested changes
I will change the commit to:
```
kernel parameters: disable IPv6

IPv6 in SEAPATH has not been taken into account and tested. For security reasons it is better to disable it.
The IPv6 disabling is done in kernel parameters to avoid givin the possibility de re-enabled at runtime.
The IPv6 can easily be restored if necessary by deleting the kernel parameter.
```

2022-01-24 08:45 UTC, dupremathieu approved these changes

2022-01-31 10:34 UTC, ebail approved these changes
LGTM, Thanks

2022-01-31 11:59 UTC, merged