no dns
seapath/meta-seapath pull request #61
Opened 2022-01-20 17:35 UTC by insatomcat

to empty the dns list in the original image

2022-01-21 08:29 UTC, ebail requested changes
Hi Thanks for your work.

I would rework the commit message. It might sound picky but I believe it is important for the history of the project.

As described in https://github.com/seapath/.github/blob/main/CONTRIBUTING.md#styleguides,
please "Use the imperative mood in the subject line". 
I would commit:

systemd: change resolved.conf

Modify resolved.conf to do X,Y and Z.

Take libvirt recipe from meta-XXX to bump its version to 6.3.0.
Libvirt 6.3.0 is required to do X, Y and Z.

Thanks

2022-01-21 09:33 UTC, dupremathieu requested changes
I will change the commit to:
```
recipes-core/systemd: remove default DNS server

By default systemd-resolved, the DNS client use by SEAPATH use Google
DNS servers is there no DNS server configured by systemd-networkd to
always have a DNS server configured.

In SEAPATH the DNS servers configuration is done during the setup step
is if during this step no DNS server was provided we condidered it is
besause it is wanted and we do not want to failback to Google DNS
servers.
```

2022-01-24 08:51 UTC, dupremathieu approved these changes

2022-01-31 10:34 UTC, ebail approved these changes
LGTM, Thanks

2022-01-31 11:58 UTC, merged