Pacemaker vm stability
seapath/meta-seapath pull request #63
Opened 2022-01-20 18:00 UTC by insatomcat

make pacemaker more stable when a host in cleanly shutdown
If there is a problem, then the timeout is 2min, clearly enough (instead of 30min).
at the same time, make journald have persistent logs so that we can investigate the previous shutdown process

2022-01-21 08:39 UTC, ebail requested changes
Hi Thanks for your work.

I would rework the commit message. It might sound picky but I believe it is important for the history of the project.

As described in https://github.com/seapath/.github/blob/main/CONTRIBUTING.md#styleguides.

I would commit:

pacemaker: modify service dependencies 

Change pacemaker dependencies to to X, Y and Z.


Thanks

2022-01-21 08:39 UTC, ebail commented on recipes-cgl/pacemaker/files/pacemaker.service
> +#necessary for the live migration to work when a host is shutdown or rebooted
shutdowned

2022-01-21 10:33 UTC, insatomcat commented on recipes-cgl/pacemaker/files/pacemaker.service
> +#necessary for the live migration to work when a host is shutdown or rebooted
changed

2022-01-24 08:51 UTC, dupremathieu approved these changes

2022-01-31 10:33 UTC, ebail approved these changes
LGTM, Thanks

2022-01-31 11:52 UTC, merged