Add support for booting on Intel NUC (tested on Kaby Lake)
seapath/meta-seapath pull request #7
Opened 2021-01-11 14:53 UTC by salerio-gs

2021-01-25 13:15 UTC, ebail requested changes
Thanks for your PR. I would split that and keep only "NUC" specific configuration in a fragment and add the others (usb3, NVME) into the global defconfig file. I would also define a specific Yocto machine for NUC. It is better rather than dealing with a global Kernel configuration for all plarform.
Please ping me so that we can work on that.

2021-01-25 13:15 UTC, ebail commented on recipes-kernel/linux/linux-mainline-rt/intel-nuc.cfg
> +CONFIG_USB_XHCI_PLATFORM=y
This configuration should be probably to linux-mainline-rt defconfig instead of dedicated fragment for Intel NUC

2021-01-25 13:15 UTC, ebail commented on recipes-kernel/linux/linux-mainline-rt/intel-nuc.cfg
> +CONFIG_MMC_BLOCK_MINORS=8
Same here. I am not sure this configuration is dedicated to NUC support

2021-01-25 13:15 UTC, ebail commented on recipes-kernel/linux/linux-mainline-rt/intel-nuc.cfg
> +CONFIG_X86_INTEL_LPSS=y
This is probably needed for Intel NUC

2021-01-25 13:15 UTC, ebail commented on recipes-kernel/linux/linux-mainline-rt/intel-nuc.cfg
> +CONFIG_BLK_DEV_NVME=y
NVME support should be added on defconfig as well

2021-01-28 09:00 UTC, salerio-gs commented
@ebail reworked as suggested.

2021-02-08 13:20 UTC, ebail reviewed
Your rework looks "good".
Please:
1- Squash your commits
2. Write a commit message according to commit message rules (see: https://wiki.lfenergy.org/display/HOME/SEAPATH#SEAPATH-Contributionprocess)
3. Please use GE copyright in votp-nuc.conf instead of RTE copyright

2021-02-08 13:34 UTC, salerio-gs commented
No problem...

2021-02-20 09:38 UTC, closed without merging